language: c
sudo: false
branches:
only:
  - master
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes psutil yaml pyyaml
  - conda-env create -f https://github.com/darribas/gds_env/raw/v6.0/gds_py/gds_py.yml
  - source activate gds
  - pip install -r https://github.com/darribas/gds_env/raw/v6.0/gds_py/gds_py_pip.txt

script: 
    #- jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 --allow-errors check_gds_stack.ipynb --stdout
  - jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 gds_py/check_py_stack.ipynb
    #- conda list --explicit
    #- source activate gds_fixed
    #- jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 check_gds_stack.ipynb

notifications:
    email:
        recipients:
            - daniel.arribas.bel@gmail.com
        on_failure: always


