SHELL = /bin/bash
# make command [image=image_name]
DOCKERRUN = docker run --rm -v "$(CURDIR)":/home/jovyan/test
DATE_STAMP = $(shell date +%Y-%m-%d)_$(ARCH)
ARCH := $(shell uname -m)
image ?= gds:$(DATE_STAMP)
code_image ?= gds_code:$(DATE_STAMP)
agent_image ?= gds_agent:$(DATE_STAMP)
GDSA_BIN ?= $(HOME)/.local/bin/gdsa
GDSA_BIN_DIR := $(patsubst %/,%,$(dir $(GDSA_BIN)))
ifeq ($(ARCH), x86_64)
	    ARCH := amd64
endif
ifeq ($(ARCH), aarch64)
	    ARCH := arm64
endif

# env/gds.yml is the single source of truth; the per-arch specs are generated
# from it and gitignored (audit 3.1). `env/Dockerfile` COPYs gds_$(ARCH).yml
# from the env/ build context, and check_py_stack.ipynb reads it from the
# mounted repo at test time -- so both build and test depend on it.
SPEC = env/gds_$(ARCH).yml

$(SPEC): env/gds.yml env/generate_spec.py
	python3 env/generate_spec.py --arch $(ARCH) --out $@

env-specs: $(SPEC)

# Asks conda-forge whether the `# !arch:` flags in env/gds.yml still hold --
# they are dated claims, not facts, and arm64 coverage keeps improving
# (audit 2.5 found 48 of 56 exclusions had gone stale). Screening only; a
# solve decides. See frontend_agent/skills/env-packages/SKILL.md.
check-flags:
	python3 env/check_flags.py --source env/gds.yml

# One definition of "execute a check notebook", used by both the test_%
# pattern rule and the `test` aggregate (audit 3.3). $(1) is the stack name,
# which is also the directory and the notebook infix: env/py/check_py_stack.ipynb.
run_check = $(DOCKERRUN) $(image) start.sh /opt/conda/envs/gds/bin/jupyter nbconvert --to html --execute /home/jovyan/test/env/$(1)/check_$(1)_stack.ipynb 2>&1 | tee env/test_$(1).log

# NOTE: test_py/test_r/test_dev are deliberately NOT in .PHONY. make skips the
# implicit-rule search for phony targets, so listing them there would stop this
# pattern rule from ever matching and `make test_py` would fail outright.
test_%: $(SPEC)
	$(call run_check,$*)

# Runs all three even if one fails, prints the summary, then exits non-zero if
# any failed. PIPESTATUS[0] is the nbconvert status -- $$? would be tee's.
test: $(SPEC)
	@py=0; r=0; dev=0; \
	$(call run_check,py); \
	[ $${PIPESTATUS[0]} -eq 0 ] && py=1; \
	$(call run_check,r); \
	[ $${PIPESTATUS[0]} -eq 0 ] && r=1; \
	$(call run_check,dev); \
	[ $${PIPESTATUS[0]} -eq 0 ] && dev=1; \
	echo ""; \
	echo "========== Test Summary =========="; \
	[ $$py  -eq 1 ] && echo "  Python : PASS" || echo "  Python : FAIL (see env/test_py.log)"; \
	[ $$r   -eq 1 ] && echo "  R      : PASS" || echo "  R      : FAIL (see env/test_r.log)"; \
	[ $$dev -eq 1 ] && echo "  Dev    : PASS" || echo "  Dev    : FAIL (see env/test_dev.log)"; \
	echo "=================================="; \
	[ $$py -eq 1 ] && [ $$r -eq 1 ] && [ $$dev -eq 1 ]

write_stacks: write_py_stack write_r_stack
write_py_stack:
	$(DOCKERRUN) $(image) start.sh bash -c "conda list -n gds > /home/jovyan/test/env/py/stack_py_$(ARCH).txt"
	$(DOCKERRUN) $(image) start.sh sed -i '1iGDS image: $(image)' /home/jovyan/test/env/py/stack_py_$(ARCH).txt
	$(DOCKERRUN) $(image) start.sh /opt/conda/envs/gds/bin/python -c "import subprocess, pandas; fo=open('/home/jovyan/test/env/py/stack_py_$(ARCH).md', 'w'); fo.write(pandas.read_json(subprocess.check_output(['conda', 'list', '-n', 'gds', '--json']).decode())[['name', 'version', 'build_string', 'channel']].to_markdown());fo.close()"
	$(DOCKERRUN) $(image) start.sh sed -i "1s/^/\n/" /home/jovyan/test/env/py/stack_py_$(ARCH).md
write_r_stack:
	$(DOCKERRUN) $(image) start.sh sh -c 'Rscript -e "ip <- as.data.frame(installed.packages()[,c(1,3:4)]); print(ip)" > /home/jovyan/test/env/r/stack_r_$(ARCH).txt'
	$(DOCKERRUN) $(image) start.sh sed -i '1iGDS image: $(image)' /home/jovyan/test/env/r/stack_r_$(ARCH).txt
	$(DOCKERRUN) $(image) start.sh Rscript -e "library(knitr); ip <- as.data.frame(installed.packages()[,c(1,3:4)]); fc <- file('/home/jovyan/test/env/r/stack_r_$(ARCH).md'); writeLines(kable(ip, format = 'markdown'), fc); close(fc);"
	$(DOCKERRUN) $(image) start.sh sed -i "1s/^/\n/" /home/jovyan/test/env/r/stack_r_$(ARCH).md
write_py_explicit:
	$(DOCKERRUN) $(image) start.sh sh -c "conda list -n gds --explicit > /home/jovyan/test/env/py/stack_py_explicit_$(ARCH).txt"
website_build:
	cd website && \
	rm -rf _includes && \
	rm -rf _site
	mkdir -p website/_includes
	cp README.md website/_includes
	cp CONTRIBUTING.md website/_includes
	cp docker/install_guide.md website/_includes/docker_install_guide.md
	cp docker/build_guide.md website/_includes/docker_build_guide.md
website: website_build
	cd website && bundle exec jekyll build
	rm -rf docs
	mv website/_site docs
	cd website && rm -rf _includes
	touch docs/.nojekyll
website_local: website_build
	# https://tonyho.net/jekyll-docker-windows-and-0-0-0-0/
	# Serve until Ctrl-C. website/_includes is left in place (gitignored, and
	# regenerated by website_build); run `make website_clean` to remove it.
	cd website && \
	JEKYLL_ENV=docker bundle exec jekyll serve --host 0.0.0.0 \
				 --incremental \
				 --config  _config.yml,_config.docker.yml
website_clean:
	rm -rf website/_includes website/_site
build: $(SPEC)
	set -o pipefail; \
	rm -f env/build_$(ARCH).log && \
		cd env && \
		docker build -t $(image) \
			--build-arg GDS_ENV_VERSION=$(shell echo $(image) | cut -d: -f2) \
			--build-arg BUILDARCH=$(ARCH) \
			--progress=plain -f Dockerfile . 2>&1 | \
		tee build_$(ARCH).log && \
		docker tag $(image) gds:latest
build_code:
	set -o pipefail; \
	cd frontend_code && \
		docker build -t $(code_image) --progress=plain -f Dockerfile \
		--build-arg base_image=$(image) . 2>&1 | \
		tee build_$(ARCH).log && \
		docker tag $(code_image) gds_code:latest
build_agent:
	set -o pipefail; \
	cd frontend_agent && \
		docker build -t $(agent_image) --progress=plain -f Dockerfile \
		--build-arg base_image=$(image) \
		--build-arg CACHEBUST=$(shell date +%s) . 2>&1 | \
		tee build_$(ARCH).log && \
		docker tag $(agent_image) gds_agent:latest
	@$(MAKE) --no-print-directory install_gdsa
	@echo ""
	@echo "  Built $(agent_image) (also tagged gds_agent:latest)."
	@echo "  Run 'gdsa help' to start. First invocation prints any host-side setup you're missing."
	@echo ""

# Install the launcher symlink. Idempotent. Honours $(GDSA_BIN) override.
# On macOS, amends ~/.zshrc or ~/.bash_profile if the bin dir isn't on PATH.
install_gdsa:
	@mkdir -p "$(GDSA_BIN_DIR)"
	@ln -sf "$(CURDIR)/utils/gdsa" "$(GDSA_BIN)"
	@echo "  Linked $(GDSA_BIN) -> $(CURDIR)/utils/gdsa"
	@mkdir -p "$(HOME)/.local/share/opencode" "$(HOME)/.config/opencode"
	@echo "  Ensured opencode state/config dirs exist under $$HOME."
	@if [ ! -f "$(HOME)/.config/opencode/opencode.json" ]; then \
	  cp "$(CURDIR)/frontend_agent/opencode.json" "$(HOME)/.config/opencode/opencode.json"; \
	  echo "  Seeded ~/.config/opencode/opencode.json from frontend_agent/opencode.json"; \
	fi
	@if [ ! -f "$(HOME)/.config/opencode/tui.json" ]; then \
	  cp "$(CURDIR)/frontend_agent/tui.json" "$(HOME)/.config/opencode/tui.json"; \
	  echo "  Seeded ~/.config/opencode/tui.json from frontend_agent/tui.json"; \
	fi
	@case ":$$PATH:" in \
	  *":$(GDSA_BIN_DIR):"*) \
	    echo "  $(GDSA_BIN_DIR) is on PATH." ;; \
	  *) \
	    if [ "$$(uname -s)" = "Darwin" ]; then \
	      case "$$SHELL" in \
	        *zsh)  rc="$$HOME/.zshrc" ;; \
	        *bash) rc="$$HOME/.bash_profile" ;; \
	        *)     rc="" ;; \
	      esac; \
	      if [ -z "$$rc" ]; then \
	        echo "  Add to PATH: export PATH=\"$(GDSA_BIN_DIR):\$$PATH\""; \
	      elif grep -qs '# gds_env: gdsa PATH' "$$rc"; then \
	        echo "  PATH already configured in $$rc. Restart your shell or run: source $$rc"; \
	      else \
	        printf '\n# gds_env: gdsa PATH\nexport PATH="%s:$$PATH"\n' "$(GDSA_BIN_DIR)" >> "$$rc"; \
	        echo "  Added $(GDSA_BIN_DIR) to PATH in $$rc."; \
	        echo "  Restart your shell or run: source $$rc"; \
	      fi; \
	    else \
	      echo "  $(GDSA_BIN_DIR) not on PATH. Add: export PATH=\"$(GDSA_BIN_DIR):\$$PATH\""; \
	    fi ;; \
	esac

.PHONY: env-specs check-flags test write_stacks write_py_stack \
        write_r_stack write_py_explicit website website_build website_local \
        website_clean build build_code build_agent install_gdsa
