name: Test GDS Environment (Python) - Linux

on:
  push:
    branches: [ master ]

jobs:

  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
            auto-update-conda: true
            auto-activate-base: true
            miniforge-version: latest
            miniforge-variant: Mambaforge
            use-mamba: true

      - name: Set up GDS Env
        shell: bash -l {0}
        run: |
          mamba env create -f gds_py/gds_py.yml
          conda activate gds
          pip install --user -r gds_py/gds_py_pip.txt

      - name: Check and Log Environment
        shell: bash -l {0}
        run: |
          conda activate gds
          conda info
          # Print conda list
          conda list
          
      - name: Test Environment
        shell: bash -l {0}
        continue-on-error: false
        run: |
          conda activate gds
          jupyter nbconvert --to html --execute gds_py/check_py_stack.ipynb

      - name: Write Explicit Stack
        shell: bash -l {0}
        continue-on-error: false
        run: |
          conda activate gds
          conda list --explicit > gds_py/gds_py_explicit_${{ matrix.os }}.txt

      - name: Commit file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gds_py/gds_py_explicit_${{ matrix.os }}.txt
          git commit -m "Update explicit {{ matrix.os }} file" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
